[package]
name = "woof"
version = "1.0.0"
edition = "2021"
authors = ["eyemotif"]


[dependencies]
argh = "0.1.10"
tiny_http = "0.12.0"

[profile.release]
opt-level = "z"
panic = "abort"
strip = true 
